kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # este corresponde al nodePort que usas para Streamlit
        hostPort: 30000
        protocol: TCP
      - containerPort: 30100  # corresponde al nodePort que usas para el modelo
        hostPort: 30100
        protocol: TCP
  - role: worker
